/**
 * IPC message protocol between the Rust backend and the Node.js sidecar.
 *
 * Messages are serialised as newline-delimited JSON over stdin/stdout.
 * The Rust backend is the initiator; the sidecar responds with a stream of
 * ``SidecarEvent`` objects.
 */

// ---------------------------------------------------------------------------
// Messages sent FROM Rust → Node.js sidecar (via sidecar stdin)
// ---------------------------------------------------------------------------

/**
 * Ask the sidecar to start a new Claude streaming session.
 */
export interface SendMessageRequest {
  type: "send_message";
  /** Monotonically increasing request identifier. */
  request_id: string;
  /** The user message text. */
  message: string;
  /** Optional conversation history to include. */
  history?: ConversationTurn[];
}

/**
 * Ask the sidecar to cancel an in-flight streaming request.
 */
export interface CancelRequest {
  type: "cancel";
  request_id: string;
}

/**
 * Ask the sidecar to perform a graceful shutdown.
 */
export interface ShutdownRequest {
  type: "shutdown";
}

/** Union of all messages the Rust backend can send to the sidecar. */
export type SidecarRequest = SendMessageRequest | CancelRequest | ShutdownRequest;

// ---------------------------------------------------------------------------
// Events sent FROM Node.js sidecar → Rust (via sidecar stdout)
// ---------------------------------------------------------------------------

/**
 * A streaming text token from Claude.
 */
export interface TokenEvent {
  type: "token";
  request_id: string;
  token: string;
}

/**
 * Signals that the full Claude response for a request is complete.
 */
export interface CompleteEvent {
  type: "complete";
  request_id: string;
  /** Full concatenated response text. */
  full_text: string;
}

/**
 * Signals that an error occurred while processing a request.
 */
export interface ErrorEvent {
  type: "error";
  request_id: string;
  message: string;
}

/**
 * Signals that the sidecar is ready to accept requests.
 */
export interface ReadyEvent {
  type: "ready";
}

/** Union of all events the sidecar can emit. */
export type SidecarEvent = TokenEvent | CompleteEvent | ErrorEvent | ReadyEvent;

// ---------------------------------------------------------------------------
// Shared data shapes
// ---------------------------------------------------------------------------

/**
 * A single turn in the conversation history.
 */
export interface ConversationTurn {
  role: "user" | "assistant";
  content: string;
}

// ---------------------------------------------------------------------------
// Tauri command payloads (frontend ↔ Rust IPC)
// ---------------------------------------------------------------------------

/**
 * Payload for the ``sidecar_send_message`` Tauri command.
 */
export interface SendMessagePayload {
  /** Unique request identifier generated by the caller. */
  requestId: string;
  /** User message text. */
  message: string;
  /** Optional conversation history. */
  history?: ConversationTurn[];
}

/**
 * Payload for the ``sidecar_cancel`` Tauri command.
 */
export interface CancelPayload {
  requestId: string;
}

/**
 * Status of the sidecar process.
 */
export type SidecarStatus = "stopped" | "starting" | "ready" | "error";

/**
 * Tauri event payload emitted on the ``sidecar://token`` channel.
 */
export interface TokenPayload {
  requestId: string;
  token: string;
}

/**
 * Tauri event payload emitted on the ``sidecar://complete`` channel.
 */
export interface CompletePayload {
  requestId: string;
  fullText: string;
}

/**
 * Tauri event payload emitted on the ``sidecar://error`` channel.
 */
export interface ErrorPayload {
  requestId: string;
  message: string;
}

/**
 * Tauri event payload emitted on the ``sidecar://status`` channel.
 */
export interface StatusPayload {
  status: SidecarStatus;
}
