/**
 * IPC message protocol between the Rust backend and the Node.js sidecar.
 *
 * Messages are serialised as newline-delimited JSON over stdin/stdout.
 * The Rust backend is the initiator; the sidecar responds with a stream of
 * ``SidecarEvent`` objects.
 */

// ---------------------------------------------------------------------------
// Messages sent FROM Rust → Node.js sidecar (via sidecar stdin)
// ---------------------------------------------------------------------------

/**
 * Ask the sidecar to start a new Claude streaming session.
 */
export interface SendMessageRequest {
  type: "send_message";
  /** Monotonically increasing request identifier. */
  request_id: string;
  /** The user message text. */
  message: string;
  /** Optional conversation history to include. */
  history?: ConversationTurn[];
}

/**
 * Ask the sidecar to cancel an in-flight streaming request.
 */
export interface CancelRequest {
  type: "cancel";
  request_id: string;
}

/**
 * Ask the sidecar to perform a graceful shutdown.
 */
export interface ShutdownRequest {
  type: "shutdown";
}

/** Union of all messages the Rust backend can send to the sidecar. */
export type SidecarRequest = SendMessageRequest | CancelRequest | ShutdownRequest;

// ---------------------------------------------------------------------------
// Events sent FROM Node.js sidecar → Rust (via sidecar stdout)
// ---------------------------------------------------------------------------

/**
 * A streaming text token from Claude.
 */
export interface TokenEvent {
  type: "token";
  request_id: string;
  token: string;
}

/**
 * Signals that the full Claude response for a request is complete.
 */
export interface CompleteEvent {
  type: "complete";
  request_id: string;
  /** Full concatenated response text. */
  full_text: string;
}

/**
 * Signals that an error occurred while processing a request.
 */
export interface ErrorEvent {
  type: "error";
  request_id: string;
  message: string;
}

/**
 * Signals that the sidecar is ready to accept requests.
 */
export interface ReadyEvent {
  type: "ready";
}

/**
 * Tauri event payload emitted on the ``sidecar://tool_call`` channel when an
 * MCP tool is invoked by Claude during a streaming session.
 */
export interface ToolCallPayload {
  /** Matches the ``requestId`` of the conversation turn. */
  requestId: string;
  /** Unique identifier for this tool invocation. */
  toolCallId: string;
  /** Name of the MCP tool being called. */
  name: string;
  /** Arguments passed to the tool. */
  args: Record<string, unknown>;
}

/**
 * Tauri event payload emitted on the ``sidecar://tool_result`` channel when
 * an MCP tool call completes (successfully or with an error).
 */
export interface ToolResultPayload {
  /** Matches the ``requestId`` of the conversation turn. */
  requestId: string;
  /** Matches the ``toolCallId`` from the corresponding ``ToolCallPayload``. */
  toolCallId: string;
  /** Serialised result from the tool. */
  result: string;
  /** Whether the tool call encountered an error. */
  isError: boolean;
}

/** Union of all events the sidecar can emit. */
export type SidecarEvent = TokenEvent | CompleteEvent | ErrorEvent | ReadyEvent;

// ---------------------------------------------------------------------------
// Shared data shapes
// ---------------------------------------------------------------------------

/**
 * A single turn in the conversation history.
 */
export interface ConversationTurn {
  role: "user" | "assistant";
  content: string;
}

// ---------------------------------------------------------------------------
// Tauri command payloads (frontend ↔ Rust IPC)
// ---------------------------------------------------------------------------

/**
 * Payload for the ``sidecar_send_message`` Tauri command.
 */
export interface SendMessagePayload {
  /** Unique request identifier generated by the caller. */
  requestId: string;
  /** User message text. */
  message: string;
  /** Optional conversation history. */
  history?: ConversationTurn[];
}

/**
 * Payload for the ``sidecar_cancel`` Tauri command.
 */
export interface CancelPayload {
  requestId: string;
}

/**
 * Status of the sidecar process.
 */
export type SidecarStatus = "stopped" | "starting" | "ready" | "error";

/**
 * Configuration for a single MCP server that the sidecar should load as a
 * tool provider for Claude Code sessions.
 */
export interface McpServerConfig {
  /** Human-readable label for this MCP server. */
  name: string;
  /** Path to the MCP server executable or script. */
  command: string;
  /** Command-line arguments for the MCP server process. */
  args: string[];
  /** Optional environment variables to set for the MCP server process. */
  env?: Record<string, string>;
}

/**
 * MCP configuration sent to the sidecar via the ``sidecar_set_mcp_config``
 * Tauri command.  Replaces the current MCP server list and optional system
 * prompt for all future Claude sessions.
 */
export interface SidecarMcpConfig {
  /** List of MCP servers to load as tool providers. */
  mcpServers: McpServerConfig[];
  /**
   * Optional system prompt prepended to every Claude session.  Useful for
   * giving Claude context about the project and its role as an Epik planning
   * assistant.
   */
  systemPrompt?: string;
}

/**
 * Payload for the ``sidecar_set_mcp_config`` Tauri command.
 */
export interface SetMcpConfigPayload {
  config: SidecarMcpConfig;
}

/**
 * Tauri event payload emitted on the ``sidecar://token`` channel.
 */
export interface TokenPayload {
  requestId: string;
  token: string;
}

/**
 * Tauri event payload emitted on the ``sidecar://complete`` channel.
 */
export interface CompletePayload {
  requestId: string;
  fullText: string;
}

/**
 * Tauri event payload emitted on the ``sidecar://error`` channel.
 */
export interface ErrorPayload {
  requestId: string;
  message: string;
}

/**
 * Tauri event payload emitted on the ``sidecar://status`` channel.
 */
export interface StatusPayload {
  status: SidecarStatus;
}
